// <auto-generated />
namespace SimpleBilling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class billing55 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billing55));
        
        string IMigrationMetadata.Id
        {
            get { return "202005150107125_billing55"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
