// <auto-generated />
namespace SimpleBilling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class bill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bill));
        
        string IMigrationMetadata.Id
        {
            get { return "202004242118089_bill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
