// <auto-generated />
namespace SimpleBilling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class billing61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billing61));
        
        string IMigrationMetadata.Id
        {
            get { return "202005170702046_billing61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
