// <auto-generated />
namespace SimpleBilling.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newBilling6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newBilling6));
        
        string IMigrationMetadata.Id
        {
            get { return "202005022354500_newBilling6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
